name: CI build

on: 
  push:
    paths-ignore: ['keymap_drawer.config.yaml', 'svg/**']
  pull_request:
    paths-ignore: ['keymap_drawer.config.yaml', 'svg/**']
    workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
